version: '3.8'

services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY:-local}/api:latest
    container_name: vhybz-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./.env:/app/.env:ro
    environment:
      - DB_PATH=/data/app.db
      # Add other environment variables as needed
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3 